language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq check cmake
script:
  - cd build
  - cmake ..
  - make all test
branches:
  only:
    - master
