language: c
compiler:
- gcc
- clang
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq check cmake
install:
- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar -xzf lcov_1.11.orig.tar.gz
- sudo make -C lcov-1.11/ install
- gem install coveralls-lcov
before_script:
- lcov --directory . --zerocounters
- cd build
script:
- cmake -DCMAKE_BUILD_TYPE=Debug ..
- make all
- ctest -V
after_success:
- cd lib
- lcov --directory . --capture --output-file coverage.info
- lcov --list coverage.info
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
branches:
  only:
  - master
